name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Change Directory to SafeAgainst.Extensions and Run Commands
      run: |
        cd SafeAgainst.Extensions
        dotnet restore
        dotnet build --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
        dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
